---
title: "Week 4 Exercise 3"
output: html_notebook
---

```{r}
library(ggplot2)

link='https://github.com/EvansDataScience/data/raw/master/eduwa.rda'

#getting the data TABLE from the file in the cloud:
load(file=url(link))
```

```{r}
table(eduwa$High.Grade,exclude = 'nothing')
```

```{r}
frqTabO=as.data.frame(prop.table(table(eduwa$High.Grade)))
names(frqTabO)=c('grade','pct')
frqTabO
```


```{r}
box1 = ggplot(eduwa, aes(y=as.numeric(High.Grade), x='')) 
box1 = box1 + geom_boxplot() + coord_flip() # to show it horizontally

# the labels use the original ordinal levels
ordLabels= levels(eduwa$High.Grade)

box2 = box1 + scale_y_continuous(labels=ordLabels,breaks=1:15)
box2
```

###Exercise 3.1: Make sure our box plot follows the same design approach and include all the elements as in the bar plot for nominal data.

```{r}
boxplot_title = "Box Plot of Highest Grade Offered in Washington Schools"
source.text = 'Source: US Department of Education'
box3=box2 + labs(title=boxplot_title,
                     x =NULL, 
                     y = 'Grade Level',
                     caption = source.text)

box4 = box3 + theme(panel.background = element_rect(fill = "white",
                                                    colour = "grey50"),
                    plot.title = element_text(hjust = 0.5),
                    plot.caption = element_text(hjust=0))
box4
```


###Exercise 3.2:
Make a histogram for the variable FREE LUNCH, and make sure it has all the right elements, and get rid of unnecessary elements.

```{r}
names(eduwa)
```


```{r}
length(unique(eduwa$Free.Lunch))

summary(eduwa$Free.Lunch)
```

```{r}
eduwa3=eduwa[complete.cases(eduwa$Free.Lunch),] #getting rid of missings
```

```{r}

base= ggplot(eduwa3,aes(x = Free.Lunch))  
h1= base + geom_histogram(color="black", fill="white", binwidth = 75,boundary=0) #changing width
h2= h1 + stat_bin(binwidth = 75, aes(label=..count..), 
                  geom = "text",boundary = 0,vjust=-0.5)

hist.title = "Histogram of Number of Students Served Free Lunch in Washington Schools"

h3 = h2 + theme(panel.background = element_rect(fill = "white",
                                                    colour = "grey50"),
                    plot.title = element_text(hjust = 0.5),
                    plot.caption = element_text(hjust=0)) + labs(title=hist.title,
                     x ="Number of Students Served Free Lunch", 
                     y = "Frequency",
                     caption = source.text)

h3


```

####Exercise 3.4 : histogram and density plot using ggplot for student teacher ratio

```{r}
eduwa4=eduwa[complete.cases(eduwa$Student.Teacher.Ratio),]

tapply(eduwa4$Student.Teacher.Ratio, 
       eduwa4$County, 
       mean)
```

```{r}
#create a dataframe with information to be plotted (mean student teacher ratio by county)
eduwa5=as.data.frame(tapply(eduwa4$Student.Teacher.Ratio, 
       eduwa4$County, 
       mean))
names(eduwa5)=c('Student.Teacher.Ratio')


```

```{r}

base = ggplot(eduwa5, aes(x=Student.Teacher.Ratio)) 

hist1 = base +  geom_histogram(color="black", fill="white", binwidth = 2 ,boundary=0)

hist.title2 = "Histogram of Average Student Teacher Ratios in Washington Counties"
  
hist2 = hist1 + theme(panel.background = element_rect(fill = "white",
                                                    colour = "grey50"),
                    plot.title = element_text(hjust = 0.5),
                    plot.caption = element_text(hjust=0)) + labs(title=hist.title2,
                     x ="Student Teacher Ratio", 
                     y = "Frequency",
                     caption = source.text)
hist3 = hist2 + scale_x_continuous(breaks=seq(0,24,2)) #adding more tick marks on the x axis

hist4 = hist3 + scale_y_continuous(breaks=seq(0,20,5)) # tick marks on y axis

hist5 = hist4 + geom_vline(aes(xintercept = mean(eduwa5$Student.Teacher.Ratio),colour="mean"),
                           show.legend  = TRUE) +
                geom_vline(aes(xintercept = median(eduwa5$Student.Teacher.Ratio),colour="median"),
                           show.legend  = TRUE) + 
                scale_color_manual(name = NULL, 
                                   values = c(median = "blue", mean = "red"))
hist5

```

